7 vote on article
Isaac-Sturtridge/nc-news pull request #5
Opened 2023-12-12 11:16 UTC by Isaac-Sturtridge

Adds voting to an article with optimistic rendering. Error handling is a bit basic at the moment, awaiting later taught content & task 12 to focus on it, for now...

2023-12-12 14:59 UTC, itskatherine reviewed
Hi Isaac, really solid start just need to fix the error handling of the voting - I've outlined how you can test an error below - once you've done this please resubmit 🙂

2023-12-12 14:59 UTC, itskatherine commented on src/components/VoteButton.jsx
> +            setViewVotes(err)
If the patch request goes wrong (which you can imitate by going to the Network tab in your dev tools  and changing 'no throttling' to 'offline') you set the votes (which starts its life as a number) to a large error object which results in the app crashing. 
You may find this section of the optimistic rendering notes useful in working out how to handle the error here: https://notes.northcoders.com/courses/js-front-end/ui-behaviours-and-optimistic-rendering#error-handling

2023-12-12 14:59 UTC, itskatherine commented on src/components/VoteButton.jsx
> +    }
Really nice start when it comes to implementing optimistic rendering here - and you've nearly got it apart from handling when there's an error and the votes need to be rectified to reflect it.

2023-12-12 14:59 UTC, itskatherine commented on src/components/VoteButton.jsx
> +  );
You could consider using something a bit more intuitive like 👍 or 👎 icons to indicate increasing and decreasing votes, or using react-icons
This isn't mandatory, just something you could consider!

2023-12-13 08:27 UTC, 2202Hannah requested changes
Hi Isaac, great start implementing Katherine's changes. There is one more thing you need to consider, when the axios request has an error and we go in to the catch block  you will need to make sure that the vote amount reverts back to what it was originally to reflect the patch not working. This will need to be handled in both the increase and decrease votes functions.

2023-12-13 10:38 UTC, Harrison365 commented on src/components/VoteButton.jsx
> +    }
Appears to be fixed :)

2023-12-13 10:38 UTC, Harrison365 commented on src/components/VoteButton.jsx
> +  );
👍

2023-12-13 10:45 UTC, Harrison365 commented on src/components/VoteButton.jsx
> +  );
👍

2023-12-13 10:45 UTC, Harrison365 commented on src/components/VoteButton.jsx
> +    }
Seems to be fixed 👍

2023-12-13 10:54 UTC, merged